### ISSUE TITLE
Api is showing 0 followers since 14.03.2018

### ISSUE THREAD

**Issue by simzik** [witnessmenow/arduino-instagram-stats#1]

**Comment by Konstantin4444** [comment]
Именно так. У меня стало показывать 0 подписчиков...
В чём проблема?

**Comment by witnessmenow** [comment]
Looks like something has changed, will need to take a look

**Comment by witnessmenow** [comment]
Fixed in c6953689c1b728dbda70d94f60906620eb0c27f3 which is now in master.

They changed the name of a property from follower_count to edge_follower_count

Would be great if you could test it out, I did and it seemed to work fine

Will be pushing a release for Arduino Library manager now (V1.0.1)

**Comment by simzik** [comment]
Perfect, Everything is working like charm agai. Huge Thanks @towitnessmenow

**Comment by Konstantin4444** [comment]
Спасибо! Всё заработало))) Брайан, ты молодец!!! Настолько просто брать статистику instagram, без своего api, - такого я нигде не видел.
