### ISSUE TITLE
I am not getting any "count" anymore

### ISSUE THREAD

**Issue by bmanos** [witnessmenow/arduino-instagram-stats#3]
Hello and thanks for the library
I try your example a few weeks ago and the first think I notice is that the followed_by suddenly change to edge_followed_by but that was easy to change. My problem is since yesterday that I get only count= 0 and when I try to get the json page with ?__a=1 I get nothing.
Is there any chance that you might have a look at this
Thanks in advance
Emmanuel

**Comment by witnessmenow** [comment]
Looks like they shut down the ?__a=1 endpoint, I get an unauthenticated error when I try hit it.

Pity, its been working for over a year!

I think I'm going to try parse the follower count directly from the webpage, the Followers stat is available in the meta tags which are right up the top of the page so it should be doable. When I get a chance to do it is another story....

**Comment by witnessmenow** [comment]
Fixed in 84b55b4

**Comment by witnessmenow** [comment]
Looks the normal webpage has the same JSON data in in a variable called window._sharedData, so I am just parsing that out and putting it through the same JSON parser as before. Seems to be working fine for me anyways

**Comment by bmanos** [comment]
Thanks Brian
Ignore the message Brian
I just comment out all those lines and it works fine
Thanks again



I made those changes but now I get those errors


`C:\Users\manos\Documents\Arduino\libraries\InstagramStats\src\InstagramStats.cpp: In member function 'InstagramUserStats InstagramStats::getUserStats(String)':
C:\Users\manos\Documents\Arduino\libraries\InstagramStats\src\InstagramStats.cpp:106:7: error: '_debug' was not declared in this scope
   if (_debug) Serial.println("starting getUserStats function");
       ^
C:\Users\manos\Documents\Arduino\libraries\InstagramStats\src\InstagramStats.cpp:124:9: error: '_debug' was not declared in this scope
     if (_debug) Serial.println(".... connected to server");
         ^
C:\Users\manos\Documents\Arduino\libraries\InstagramStats\src\InstagramStats.cpp:136:13: error: '_debug' was not declared in this scope
         if (_debug) Serial.print(c);
             ^
C:\Users\manos\Documents\Arduino\libraries\InstagramStats\src\InstagramStats.cpp:158:15: error: '_debug' was not declared in this scope
           if (_debug) Serial.println("finished");
               ^
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).`
